.ifndef _KEYBOARD_H_
_KEYBOARD_H_ = 1

KBD_KEY_SPACE        = $20
KBD_KEY_ENTER        = $0d
KBD_KEY_ESCAPE       = $1b
KBD_KEY_BACKSPACE    = $7f
KBD_KEY_ARROW_UP     = $0b
KBD_KEY_ARROW_DOWN   = $0a
KBD_KEY_ARROW_LEFT   = $08
KBD_KEY_ARROW_RIGHT  = $15
KBD_KEY_TAB          = $09
KBD_KEY_PAGE_UP      = $19
KBD_KEY_PAGE_DOWN    = $1a
KBD_KEY_CTRL_X       = $18

.endif
