#!/bin/bash
EXECUTABLE="x65c02"
LDFLAGS="-O2 -lpthread -Wall -lncurses"
SRCDIR=src

objects_string=""
for i in $(find src -type f -name "*.c" | sed -e 's/\.c$//');
do
	cc -I $SRCDIR -c $i".c" -o $i".o" -g
	objects_string="$objects_string "$i".o "
done;

cc -o $EXECUTABLE $objects_string $LDFLAGS

rm $objects_string
